package Database::Temp::Driver::Base;
## no critic (Documentation::RequirePodAtEnd)
## no critic (Documentation::RequirePodSections)

use strict;
use warnings;

# ABSTRACT: Base class for all driver in package Database::Temp

# VERSION: generated by DZP::OurPkgVersion

use Moo;
use Types::Standard qw( Str Int HashRef CodeRef Maybe );

=pod

=encoding utf8

=for Pod::Coverage ^(name|args|cleanup|init|deinit|dsn|username|password|attr)$

=cut

=head1 DESCRIPTION

The base class for all drivers.

=cut

has name => (
    is => 'ro',
    isa => Str,
);
has args => (
    is => 'ro',
);

has cleanup => (
    is => 'rw',
    isa => Int->where( '$_ == 1 || $_ == 0' ),
);
has init => (
    is      => 'ro',
    isa     => Maybe[CodeRef],
    # isa     => sub { croak if( ref $_[0] !~ m/(SCALAR|CODE)/ ) },
    default => sub {
        return sub { };
    },
);

has deinit => (
    is      => 'ro',
    isa     => Maybe[CodeRef],
    # isa     => sub { croak if( ref $_[0] !~ m/(SCALAR|CODE)/ ) },
    default => sub {
        return sub { };
    },
);

# Connection info
has dsn => (
    is      => 'rw',
    isa => Str,
);
has username => (
    is      => 'rw',
);
has password => (
    is      => 'rw',
);
has attr => (
    is      => 'rw',
    isa => HashRef,
);

1;
